apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    labels:
        app: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            initContainers:
                - name: wait-for-mongodb
                  image: busybox:1.36.1 # 軽量なイメージ
                  command:
                      [
                          "sh",
                          "-c",
                          "until nc -z mongodb-service 27017; do echo waiting for mongodb; sleep 2; done;",
                      ]
            containers:
                - name: backend
                  image: nextjs-chat-backend:latest # minikube用
                  ports:
                      - containerPort: 5000
                  env:
                      - name: MONGO_URI
                        value: mongodb://root:rootpassword@mongodb-service:27017/chatdb?authSource=admin # MongoDBサービス名を使用
                      - name: JWT_SECRET
                        value: your_jwt_secret_key
                      - name: FRONTEND_URL
                        value: http://chat.local
                  imagePullPolicy: Never # ローカルイメージを使用するため
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 5000
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    type: ClusterIP # 内部アクセスのみ
